---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: thanos-secret
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    {{- /* read the bucket data and endpoint access data */ -}}
    {{- $bucket := (fromConfigMap "open-cluster-management-addon-observability" "rhacm-observability" "BUCKET_NAME" ) }}
    {{- $endpoint := (fromConfigMap "open-cluster-management-addon-observability" "rhacm-observability" "BUCKET_HOST" ) }}
    {{- $access_key := (fromSecret "open-cluster-management-addon-observability" "rhacm-observability" "AWS_ACCESS_KEY_ID" | base64dec) }}
    {{- $secret_key := (fromSecret "open-cluster-management-addon-observability" "rhacm-observability" "AWS_SECRET_ACCESS_KEY" | base64dec) }}
    {{- /* create the thanos config file as a template */ -}}
    {{- $thanosConfig := `
    type: s3
    config:
      bucket: %s
      endpoint: %s
      insecure: true
      access_key: %s
      secret_key: %s
    ` }}
      {{- /* create the secret using the thanos configuration template created above. */ -}}
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: thanos-object-storage
          namespace: open-cluster-management-observability
        type: Opaque
        data:
          thanos.yaml: {{ (printf $thanosConfig $bucket
                                                $endpoint
                                                $access_key
                                                $secret_key
                          ) | base64enc }}
