---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../base/

helmCharts:
- name: argocd-app-of-app
  version: 0.2.6
  valuesFile: values.yaml
  namespace: cluster-management
  releaseName: argocd-app-of-app-0.2.6
