---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: openshift-monitoring
placementBindingDefaults:
  name: "placementbinding-openshift-monitoring"
policyDefaults:
  namespace: example-policies-hub
  consolidateManifests: false
  categories:
  - OM Observability Management
  controls:
  - OM OpenShift Monitoring
  standards:
  - Example Baseline 2023v1
  remediationAction: inform
  complianceType: musthave
  pruneObjectBehavior: "DeleteIfCreated"
policies:

- name: openshift-monitoring
  manifests:
  - path: openshift-monitoring/
  remediationAction: enforce

policySets:
- name: "openshift-monitoring"
  description: "Cluster-Monitoring setup"
  policies:
  - openshift-monitoring
  placement:
    placementPath: placement.yaml

